// Auto-generated from Mindstate Personas by Will Leach
// Behavioral psychology framework for AI-powered ad generation

export interface MindstateProfile {
  id: string;
  name: string;
  approach: "cautious" | "optimistic";
  motivation: string;
  coreDescription: string;
  goalToActivate: string;
  approachFraming: string;
  triggers: string[];
  feelingsToEvoke: string[];
  feelingsToAvoid: string[];
  visualGuidance: string;
  copyTone: string;
  copyGuidance: string;
  exampleHeadlines: string[];
  contentStrategy: string;
}

export const MINDSTATE_FRAMEWORK_OVERVIEW = "Mindstate Marketing Framework (Will Leach)\n\nAPPROACH: How people make decisions\n- Cautious (Loss-Avoidance): Focus on avoiding mistakes, minimizing risk, preventing loss\n- Optimistic (Gain-Seeking): Focus on gaining benefits, pursuing opportunities, maximizing upside\n\nMOTIVATION: 8 Universal Human Motivations\n1. Achievement - Desire for success, accomplishment, overcoming obstacles\n2. Autonomy - Desire for freedom, independence, self-determination  \n3. Belonging - Desire for acceptance, connection, community\n4. Competence - Desire for mastery, skill development, personal growth\n5. Empowerment - Desire for control, agency, being equipped\n6. Engagement - Desire for curiosity, stimulation, novelty\n7. Esteem - Desire for status, respect, recognition\n8. Nurturance - Desire to care for others, help, provide support\n9. Security - Desire for safety, stability, predictability\n\nTHE 3-STEP ACTIVATION PROCESS:\nStep 1 - IDENTIFY: Determine customer's dominant mindstate (motivation + approach combination)\nStep 2 - PRIME: Activate the specific motivation through messaging and emotional cues\nStep 3 - FRAME: Present brand/product in a way that matches their psychological approach\n\nKEY PRINCIPLES FOR AI AD GENERATION:\n- Use cognitive triggers (heuristics) to make decisions feel intuitive\n- Lead with visuals that evoke desired emotional states\n- Reinforce with copy that validates the emotional connection\n- Ensure consistency: every touchpoint reflects the same psychological position\n";

export const MINDSTATE_PROFILES: MindstateProfile[] = [
  {
    id: "cautious-achievement",
    name: "Cautious Achievement",
    approach: "cautious",
    motivation: "achievement",
    coreDescription: "Driven to achieve a sense of accomplishment by being persistent and relentless to avoid mistakes or barriers to achieve their goals. In this mindstate, people will look for strategies to help them avoid mistakes by limiting risk or chances. Desire tools that help them reduce risk",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher order, aspirational goals, thereby making your brand more salient and meaningful in key decision moments. To successfully reach their goals by maximizing their potential t",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Peak End Rule: The tendency to judge an entire experience largely based on how they.",
      "Egocentric Bias: The tendency to believe that positive results are the result of your.",
      "Sunk Cost Fallacy: The tendency to justify increased investment of money, time, lives,.",
      "Self-Justification: The tendency to justify a behavior and deny any negative feedback."],
    feelingsToEvoke: ["Tenacious", "Worthy", "Closure", "Determined", "Successful", "Victorious", "Accomplishment"],
    feelingsToAvoid: ["Inferior", "Unmotivated", "Complacent", "Unsuccessful", "Overcome", "Failure", "Ineffective"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on accomplishment, determination, and success. Some examples of pictures that c",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone The tone of advertising copy for the brand should be professional, confident, ",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone The tone of advertising copy for the brand should be professional, confident, and results-oriented. The copy should emphasize the brand's expertise and track record of success in achieving goals and removing obstacles. It should",
    exampleHeadlines: ["Unleash your true potential with [BRAND].\u201c", "Be bold, be daring, be unbounded\u201d Our brand empowers you to take risks and create your own path to success.", "Don't settle for one-size-fits-all solutions. Customize your experience", "Be the architect of your own life and design the perfect solution for your unique needs with our customizable tools.", "Step into your own unique journey. [Brand] lets you create a path that's tailored to your individual needs."],
    contentStrategy: "",
  },
  {
    id: "cautious-autonomy",
    name: "Cautious Autonomy",
    approach: "cautious",
    motivation: "autonomy",
    coreDescription: "Driven to feel distinct by expressing their unique preferences to avoid restrictions to their freedom of choice. In this mindstate, people seek to avoid being restricted or controlled in their ability to reach their goal. Desire tools that help them get what they want, in the way",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals thereby making your brand more salient and meaningful in key decision moments. To successfully reach their goals by avoiding things that may less",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Egocentric Bias: The tendency to believe that positive results are the result of individual.",
      "Projection Bias: The tendency to falsely project current preferences onto future.",
      "Endowment Effect: The tendency to ascribe more value to things merely because they.",
      "IKEA Effect: The tendency to place a disproportionately high value on products that."],
    feelingsToEvoke: ["Independent", "Authentic", "Surprising", "Distinct", "Unique", "Different", "Free"],
    feelingsToAvoid: ["Dependent", "Restricted", "Predictable", "Conforming", "Limited", "Controlled", "Forgettable"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on freedom, individuality, and personalization. Some examples of pictures that ",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be positive, encouraging, and enthusiastic w",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be positive, encouraging, and enthusiastic while conveying a sense of excitement about the possibilities of freedom of choice and personalization. In addition, copy should inspire consumers to f",
    exampleHeadlines: ["Unleash your unique potential with our customizable solutions.", "Choose your own path with [BRAND].", "Experience the freedom of self-determination with our personalized approach.", "Create a one-of-a-kind experience that reflects you.", "Find your perfect fit with our solutions designed for your unique needs."],
    contentStrategy: "",
  },
  {
    id: "cautious-belonging",
    name: "Cautious Belonging",
    approach: "cautious",
    motivation: "belonging",
    coreDescription: "Driven to feel accepted by others by avoiding mistakes that may cause them to be excluded by others. When in this mindstate, people seek to validate their core sense of social acceptance through avoiding repudiation by a larger group. Desire tools that help them establish and mai",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by maximizing things that i",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Conformity Effect: The tendency to feel more secure in an action when we know that.",
      "In-Group Bias: The tendency to give people preferential treatment because we.",
      "Reciprocity: The tendency to desire to repay, in kind, for what another person has.",
      "Inequality Aversion: The tendency to desire fairness and resistance to incidental."],
    feelingsToEvoke: ["Agreement", "Unity"],
    feelingsToAvoid: ["Conflict", "Rejected", "Accepted", "Left out", "Harmony", "Isolated", "Connected", "Separated"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on community, connection, and inclusivity. They should feature people of differ",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be supportive, trustworthy, and inclusive. T",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be supportive, trustworthy, and inclusive. The copy should be written in a way that is easy for the audience to understand and relate to, highlighting the practical and cautious approach of the ",
    exampleHeadlines: ["Looking for a way to feel more connected and understood? [Brand Name] is here to help.", "Find your people, build your world - [Brand Name]", "Creating meaningful connections, one person at a time - [Brand Name]", "Your network is your net worth - [Brand Name]", "Better together - [Brand Name]"],
    contentStrategy: "",
  },
  {
    id: "cautious-competence",
    name: "Cautious Competence",
    approach: "cautious",
    motivation: "competence",
    coreDescription: "Driven to feel competent in activities by avoiding mistakes that may cause them to not surpass their own personal standards. When in this mindstate, people seek to avoid decreases in their expertise in an activity to validate their core sense of personal growth. Desire tools that",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by avoiding things that may",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Anchoring: The tendency to rely too heavily or \u2018anchor\u201d on one element of a choice.",
      "Egocentric Bias: The tendency to believe that positive results are the result of individual.",
      "Ambiguity Effect: The tendency to avoid options that are unclear or make the.",
      "Sunk Cost Fallacy: The tendency to continue an action, based upon the cumulative."],
    feelingsToEvoke: ["Ready", "Smart", "Limitless", "Intelligent", "Competent", "Skilled", "Exceptional"],
    feelingsToAvoid: ["Ignorant", "Simple", "Mediocre", "Constricted", "Unable", "Inferior", "Incapable"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on personal growth, excellence and skill. Some examples of pictures that could ",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be confident, authoritative, yet relatable. ",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be confident, authoritative, yet relatable. The tone should reflect the brand's unwavering commitment to personal growth and excellence, and should convey a sense of purpose, dedication, and pas",
    exampleHeadlines: ["Unlock your full potential with our proven solutions for personal growth and excellence.", "Don't settle for mediocrity. Choose our brand and strive for excellence in everything you do.", "Master your skills and avoid common pitfalls with our expert tools and guidance.", "Maximize your potential and reach your full capabilities with [BRAND].", "Choose excellence. Choose [BRAND]."],
    contentStrategy: "",
  },
  {
    id: "cautious-empowerment",
    name: "Cautious Empowerment",
    approach: "cautious",
    motivation: "empowerment",
    coreDescription: "Driven to feel empowered by decreasing variability and lack of control in pursuing their goal. In this mindstate, people will look for strategies that help better equip them with the power needed to reach their goals. Desire tools that help them control important aspects of their",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by avoiding things that may",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Ambiguity Effect: The tendency to avoid options that are unclear, making the.",
      "Inequality Aversion: The tendency to desire fairness and resistance to incidental.",
      "Confirmation Bias: The tendency to search for, interpret, and remember information.",
      "Egocentric Bias: The tendency to believe that positive results are the result of your."],
    feelingsToEvoke: ["Free"],
    feelingsToAvoid: ["Trapped", "Rudderless", "In control", "Out of control", "In charge", "Restricted", "Uninhibited", "Limited"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on accomplishment, determination, and success. Some examples of pictures that c",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be a confident and empowering tone that insp",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be a confident and empowering tone that inspires customers to take control of their lives and pursue their goals passionately and with determination. The tone should convey a sense of excitement",
    exampleHeadlines: ["Empower yourself to take control of your business with our tried-and-true strategies.\u201d", "Your goals, your way\u201d"],
    contentStrategy: "",
  },
  {
    id: "cautious-engagement",
    name: "Cautious Engagement",
    approach: "cautious",
    motivation: "engagement",
    coreDescription: "Driven to avoid mediocrity in the products, services, or experiences they buy. In this mindstate people will look for strategies that provide more experiential ways to pursue their goals. Desire tools that help them avoid boring, ordinary experiences by making them fresh and abso",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by avoiding things that may",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Peak End Rule: The tendency to judge an entire experience largely based on.",
      "Temporal Discounting: The tendency to place higher value on rewards that are.",
      "Sunk Cost Fallacy: The tendency to place higher value on continuing actions."],
    feelingsToEvoke: ["Adventurous", "Dynamic", "Captivated", "Engrossed", "In the moment", "Enthralled", "Enthusiastic"],
    feelingsToAvoid: ["Boring", "Unproductive", "Listless", "Uninvolved", "Distracted", "Unfocused", "Apathetic"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures used in promotional materials should focus on excitement, satisfaction, and engagement while being visually striking and atte",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should convey a sense of excitement, enthusiasm, an",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should convey a sense of excitement, enthusiasm, and passion for providing the best possible experiences to customers. Here are some guidelines that should be followed: Emphasize how your brand deliver",
    exampleHeadlines: ["Experience true immersion with our unique services.", "Say goodbye to mediocrity and hello to excellence.", "Fully engage in the present moment with [BRAND].", "Discover tried and true solutions for an unparalleled experience.", "Unlock the full potential of the moment"],
    contentStrategy: "",
  },
  {
    id: "cautious-esteem",
    name: "Cautious Esteem",
    approach: "cautious",
    motivation: "esteem",
    coreDescription: "Driven to feel admired and valued in activities by minimizing their risks of being unrecognized socially. When in this mindstate, people seek to maintain their chance of being noticed or special. Desire tools or products that help them decrease their chance of losing future socia",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by avoiding things that may",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Halo Effect: The tendency for positive (or negative) feelings about one entity to.",
      "Anchoring: The tendency to rely too heavily or \u2018anchor\u201d on one element of a.",
      "Egocentric Bias: The tendency to believe that positive results are the result of."],
    feelingsToEvoke: ["Admired", "Respected", "Known", "Praised", "Recognized", "Popular", "Valued"],
    feelingsToAvoid: ["Overlooked", "Forgotten", "Unknown", "Unappreciated", "Unrecognized", "Invisible", "Marginalized"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on exclusivity, sophistication, and success. Some examples of pictures that cou",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be confident, authoritative, and reassuring.",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be confident, authoritative, and reassuring. The copy should communicate a sense of expertise and reliability, emphasizing the brand's tried and true solutions and concrete examples of success t",
    exampleHeadlines: ["Don't settle for less - elevate your social standing with our proven solutions.", "Our brand is the ultimate expression of success and sophistication.", "Discover the secret to only a few know\u2026"],
    contentStrategy: "",
  },
  {
    id: "cautious-nurturance",
    name: "Cautious Nurturance",
    approach: "cautious",
    motivation: "nurturance",
    coreDescription: "Driven to achieve a sense of appreciation by providing care and support to others/themselves. When in this mindstate, people seek greater affiliation and cooperation by limiting conflict, often in an attempt to feel greater peace and harmony. Desire to make others/themselves feel",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by avoiding things that may",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Loss Aversion: People over-emphasize the value of things that they.",
      "Conformity Effect: People feel more secure in an action when we know that.",
      "In-Group Bias: The tendency to give people preferential treatment because."],
    feelingsToEvoke: ["Caring", "Supportive", "Nurtured", "Loved", "Provided for", "Taken care of", "Selfless"],
    feelingsToAvoid: ["Indifferent", "Callous", "Unloved", "Rejected", "Abandoned", "Neglected", "Selfish"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on warmth, care, and support. Some examples of pictures that could be used in a",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should have a warm, empathetic, and supportive tone",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should have a warm, empathetic, and supportive tone. In addition, the copy should convey a genuine concern for the customer\u2019s well-being, and a desire to provide them with the care and support they nee",
    exampleHeadlines: ["Let us help you achieve your goals, one nurturing step at a time."],
    contentStrategy: "",
  },
  {
    id: "cautious-security",
    name: "Cautious Security",
    approach: "cautious",
    motivation: "security",
    coreDescription: "Driven to achieve a sense of security by minimizing their risk of having to protect themselves or possessions from threats while pursuing their goals. In this mindstate, people will look for strategies to help them immediately limit any threats that can cause them or their posses",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by avoiding things that may",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Hyperbolic Discounting: The tendency to place higher value on rewards that.",
      "Loss Aversion: The tendency to over-emphasize the value of things that are.",
      "Conformity Effect: The tendency to place higher value on actions that others.",
      "Status Quo Bias: The tendency to maintain routines once they have been."],
    feelingsToEvoke: ["Calm", "Composed", "Tranquil", "Peace of mind", "Certain", "Secure", "Safe"],
    feelingsToAvoid: ["Anxious", "Nervous", "Tense", "Concerned", "Uncertain", "Insecure", "Vulnerable"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on safety, protection, and peace of mind. Some examples of pictures that could ",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should have a reassuring, informative, and trustwor",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should have a reassuring, informative, and trustworthy tone. In addition, the copy should convey a sense of security and expertise while emphasizing the concrete solutions and tried-and-true processes ",
    exampleHeadlines: [],
    contentStrategy: "",
  },
  {
    id: "optimistic-achievement",
    name: "Optimistic Achievement",
    approach: "optimistic",
    motivation: "achievement",
    coreDescription: "",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher order, aspirational goals, thereby making your brand more salient and meaningful in key decision moments. To successfully reach their goals by maximizing their potential t",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Peak End Rule: The tendency to judge an entire experience largely based on how they.",
      "Egocentric Bias: The tendency to believe that positive results are the result of your.",
      "Sunk Cost Fallacy: The tendency to justify increased investment of money, time, lives,.",
      "Self-Justification: The tendency to justify a behavior and deny any negative feedback."],
    feelingsToEvoke: ["Inferior", "Unmotivated", "Complacent", "Unsuccessful", "Overcome", "Failure", "Ineffective"],
    feelingsToAvoid: ["Tenacious", "Motivated", "Closure", "Determined", "Successful", "Victorious", "Accomplished"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on accomplishment, determination, and success. Some examples of pictures that c",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be optimistic, confident, and inspiring, hig",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be optimistic, confident, and inspiring, highlighting the benefits of persistence, taking calculated risks, and using innovative approaches to achieve success. Copy should inspire consumers to a",
    exampleHeadlines: ["Take the first step towards success with [Brand]", "Success is a Journey, [BRAND] is Your Guide", "Transforming Dreams into Reality\u201c"],
    contentStrategy: "",
  },
  {
    id: "optimistic-autonomy",
    name: "Optimistic Autonomy",
    approach: "optimistic",
    motivation: "autonomy",
    coreDescription: "Driven to feel distinct by expressing their unique preferences. In this mindstate, people will look for strategies that provide customization when pursuing their goals, even if that means adding risk. Desire tools that help them get what they want, in the way they want in the tim",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your brand more salient and meaningful in key decision moments. To successfully reach their goals by maximizing things that may i",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Egocentric Bias: The tendency to believe that positive results are the result of individual.",
      "Projection Bias: The tendency to falsely project current preferences onto future.",
      "Endowment Effect: The tendency to ascribe more value to things merely because they.",
      "IKEA Effect: The tendency to place a disproportionately high value on products that."],
    feelingsToEvoke: [],
    feelingsToAvoid: ["Dependent", "Independent", "Restricted", "Authentic", "Predictable", "Surprising", "Conforming", "Distinct"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on freedom, individuality, and personalization. Some examples of pictures that ",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be positive, encouraging, and enthusiastic w",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be positive, encouraging, and enthusiastic while conveying a sense of excitement about the possibilities of freedom of choice and personalization. In addition, copy should inspire consumers to f",
    exampleHeadlines: ["Unleash your true potential with [BRAND].\u201c", "Be bold, be daring, be unbounded\u201d Our brand empowers you to take risks and create your own path to success.", "Don't settle for one-size-fits-all solutions. Customize your experience", "Be the architect of your own life and design the perfect solution for your unique needs with our customizable tools.", "Step into your own unique journey. [Brand] lets you create a path that's tailored to your individual needs."],
    contentStrategy: "",
  },
  {
    id: "optimistic-belonging",
    name: "Optimistic Belonging",
    approach: "optimistic",
    motivation: "belonging",
    coreDescription: "Driven to feel accepted by others by finding similarities that maximize their chances of greater camaraderie and approval. When in this mindstate, people seek to validate their core sense of social acceptance through cohesiveness with a larger group. Desire tools that help them e",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by maximizing things that i",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Conformity Effect: The tendency to feel more secure in an action when we know that.",
      "In-Group Bias: The tendency to give people preferential treatment because we.",
      "Reciprocity: The tendency to desire to repay, in kind, for what another person has.",
      "Inequality Aversion: The tendency to desire fairness and resistance to incidental."],
    feelingsToEvoke: ["Conflict", "Rejected", "Left out", "Isolated", "Separated", "Division", "Lonely"],
    feelingsToAvoid: ["Agreement", "Accepted", "Harmony", "Connected", "Solidarity", "Unity", "Sociable"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on community, connection, and inclusivity. They should feature people of differ",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be friendly, approachable, and inclusive. It",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be friendly, approachable, and inclusive. It should feel personal, authentic, welcoming, and relatable, as if speaking directly to the customer and inviting them to be part of a larger community",
    exampleHeadlines: ["Get the support you need to pursue your passions and build meaningful relationships with [Brand Name].", "Looking for a way to feel more connected and understood? [Brand Name] is here to help.", "Find your people, build your world - [Brand Name]", "Creating meaningful connections, one person at a time - [Brand Name]", "Your network is your net worth - [Brand Name]"],
    contentStrategy: "",
  },
  {
    id: "optimistic-competence",
    name: "Optimistic Competence",
    approach: "optimistic",
    motivation: "competence",
    coreDescription: "Driven to feel competent in activities by maximizing the opportunities to exceed their own personal standards. When in this mindstate, people seek to increase their expertise in an activity to validate their core sense of personal growth. Desire tools that help them explore and b",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by maximizing their chance ",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Anchoring: The tendency to rely too heavily or \u2018anchor\u201d on one element of a choice.",
      "Egocentric Bias: The tendency to believe that positive results are the result of individual.",
      "Ambiguity Effect: The tendency to avoid options that are unclear or make the.",
      "Sunk Cost Fallacy: The tendency to continue an action, based upon the cumulative."],
    feelingsToEvoke: ["Ignorant", "Simple", "Mediocre", "Constricted", "Unable", "Inferior", "Incapable"],
    feelingsToAvoid: ["Ready", "Smart", "Limitless", "Intelligent", "Competent", "Skilled", "Exceptional"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on personal growth, excellence and skill. Some examples of pictures that could ",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be confident, authoritative, yet relatable. ",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be confident, authoritative, yet relatable. The tone should reflect the brand's unwavering commitment to personal growth and excellence, and should convey a sense of purpose, dedication, and pas",
    exampleHeadlines: ["Unlock your full potential with [BRAND]. Our platform empowers you to explore your passions, develop your skills, and", "Experience the joy of learning with [BRAND].", "Unleash Your Inner Greatness", "Experience Limitless Growth", "Your Journey to Mastery"],
    contentStrategy: "",
  },
  {
    id: "optimistic-empowerment",
    name: "Optimistic Empowerment",
    approach: "optimistic",
    motivation: "empowerment",
    coreDescription: "Driven to feel empowered by increasing their options and level of control in pursuing their goal. In this mindstate, people will look for strategies that help better equip them when pursuing their goals, even if that means adding risk. Desire tools that help them control importan",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by maximizing their chances",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Ambiguity Effect: The tendency to avoid options that are unclear, making the.",
      "Inequality Aversion: The tendency to desire fairness and resistance to incidental.",
      "Confirmation Bias: The tendency to search for, interpret, and remember information.",
      "Egocentric Bias: The tendency to believe that positive results are the result of your."],
    feelingsToEvoke: ["Trapped", "Rudderless", "Out of control", "Restricted", "Limited", "Weak", "Tentative"],
    feelingsToAvoid: ["Free", "In control", "In charge", "Uninhibited", "Empowered", "Strong", "Forceful"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on accomplishment, determination, and success. Some examples of pictures that c",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be a confident and empowering tone that insp",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be a confident and empowering tone that inspires customers to take control of their lives and pursue their goals passionately and with determination. The tone should convey a sense of excitement",
    exampleHeadlines: ["Take control of your life to reach your potential\u201d", "Empower yourself. Control your destiny.", "Take charge. Reach higher.", "Be resourceful. Be unstoppable.", "Limitations are just a mindset. Take control with us."],
    contentStrategy: "",
  },
  {
    id: "optimistic-engagement",
    name: "Optimistic Engagement",
    approach: "optimistic",
    motivation: "engagement",
    coreDescription: "Driven to feel that they are getting the most out of their product, service, or experience. In this mindstate people will look for strategies that provide experiential ways of pursuing their goals. Desire tools that help them live the experience to the fullest, in a way that is f",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by maximizing their ability",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Peak End Rule: The tendency to judge an entire experience largely based on.",
      "Temporal Discounting: The tendency to place higher value on rewards that are.",
      "Sunk Cost Fallacy: The tendency to place higher value on continuing actions."],
    feelingsToEvoke: ["Boring", "Unproductive", "Listless", "Uninvolved", "Distracted", "Unfocused", "Apathetic"],
    feelingsToAvoid: ["Adventurous", "Dynamic", "Captivated", "Engrossed", "In the moment", "Enthralled", "Enthusiastic"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures used in promotional materials should focus on excitement, satisfaction, and engagement while being visually striking and atte",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should convey a sense of excitement, enthusiasm, an",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should convey a sense of excitement, enthusiasm, and passion for providing the best possible experiences to customers. Here are some guidelines that should be followed: Emphasize how your brand deliver",
    exampleHeadlines: ["Find your balance with our innovative approach to X\u201d", "Say goodbye to mediocrity", "Experience the difference with us!", "Engage your senses, satisfy your soul!", "Get lost in the moment with [BRAND]"],
    contentStrategy: "",
  },
  {
    id: "optimistic-esteem",
    name: "Optimistic Esteem",
    approach: "optimistic",
    motivation: "esteem",
    coreDescription: "Driven to feel admired and valued in activities by maximizing the opportunities to be recognized socially. When in this mindstate, people seek to increase their noticeability and popularity. Desire tools or products that help them measure and improve their future social standing ",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by maximizing their chance ",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Halo Effect: The tendency for positive (or negative) feelings about one entity to.",
      "Anchoring: The tendency to rely too heavily or \u2018anchor\u201d on one element of a.",
      "Egocentric Bias: The tendency to believe that positive results are the result of."],
    feelingsToEvoke: ["Overlooked", "Forgotten", "Unknown", "Unappreciated", "Unrecognized", "Invisible", "Marginalized"],
    feelingsToAvoid: ["Admired", "Respected", "Known", "Praised", "Recognized", "Popular", "Valued"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on popularity, social status, and admiration. Some examples of pictures that co",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be confident and aspirational, emphasizing s",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should be confident and aspirational, emphasizing social recognition and validation. In addition, the copy should communicate a sense of expertise and reliability, emphasizing the brand\u2019s innovative th",
    exampleHeadlines: ["Be Seen, Be Admired, Be Valued. [BRAND].", "Get the Recognition You Deserve.", "Maximize Your Social Status with Us.\u201d"],
    contentStrategy: "",
  },
  {
    id: "optimistic-nurturance",
    name: "Optimistic Nurturance",
    approach: "optimistic",
    motivation: "nurturance",
    coreDescription: "Driven to achieve a sense of appreciation by providing care and support to others/themselves. When in this mindstate, people seek greater affiliation and cooperation, often in an attempt to feel greater trust. Desire to make others/themselves feel deserving by finding ways to inc",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by maximizing their chance ",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Loss Aversion: People over-emphasize the value of things that they.",
      "Conformity Effect: People feel more secure in an action when we know that.",
      "In-Group Bias: The tendency to give people preferential treatment because."],
    feelingsToEvoke: ["Indifferent", "Callous", "Unloved", "Rejected", "Abandoned", "Neglected", "Selfish"],
    feelingsToAvoid: ["Caring", "Supportive", "Nurtured", "Loved", "Provided for", "Taken care of", "Selfless"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on warmth, care, and support. Some examples of pictures that could be used in a",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should have a warm, caring, and supportive tone. In",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should have a warm, caring, and supportive tone. In addition, the copy should emphasize the brand's desire to help and support others and highlight its commitment to fostering trust and affiliation wit",
    exampleHeadlines: ["Join our community and experience the power of true connection.", "Join our community of compassion and connection.", "Love, support, and compassion."],
    contentStrategy: "",
  },
  {
    id: "optimistic-security",
    name: "Optimistic Security",
    approach: "optimistic",
    motivation: "security",
    coreDescription: "Driven to achieve a sense of security by maximizing their ability to protect themselves or possessions from threats while pursuing their goals. In this mindstate, people will look for strategies to help them immediately increase their ability to protect themselves from loss or pa",
    goalToActivate: "GOAL TO ACTIVATE Use this to brainstorm creative ways to activate their higher-order, aspirational goals, thereby making your messaging more salient and meaningful in key decision moments. To successfully reach their goals by maximizing their chance ",
    approachFraming: "APPROACH TO FRAME",
    triggers: ["Hyperbolic Discounting: The tendency to place higher value on rewards that.",
      "Loss Aversion: The tendency to over-emphasize the value of things that are.",
      "Conformity Effect: The tendency to place higher value on actions that others.",
      "Status Quo Bias: The tendency to maintain routines once they have been."],
    feelingsToEvoke: ["Anxious", "Nervous", "Tense", "Concerned", "Uncertain", "Insecure", "Vulnerable"],
    feelingsToAvoid: ["Calm", "Composed", "Tranquil", "Peace of mind", "Certain", "Secure", "Safe"],
    visualGuidance: "VISUAL GUIDANCE Use this to help guide your visual strategy and execution decisions in sales and marketing creative. Visual Guidance Overall, the pictures you use in promotional materials should focus on protection, trust, and reliability. Some examples of pictures that could be ",
    copyTone: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should have a serious, reassuring, and trustworthy ",
    copyGuidance: "COPY GUIDANCE Use this to help guide your copy strategy and tactical decisions in sales and marketing creative. Copy Tone Sales and Advertising copy should have a serious, reassuring, and trustworthy tone. In addition, the copy should convey a sense of comfort and peace of mind to customers, highlighting the brand's ability to protect them and thei",
    exampleHeadlines: [],
    contentStrategy: "",
  },
];

/** Format mindstate guidance for AI prompts */
export function getMindstateGuidance(profiles: MindstateProfile[]): string {
  return profiles.map(ms => `Mindstate: ${ms.name} (${ms.approach} ${ms.motivation})
Goal: ${ms.goalToActivate}
Approach: ${ms.approachFraming}
Evoke: ${ms.feelingsToEvoke.join(", ")}
Avoid: ${ms.feelingsToAvoid.join(", ")}
Triggers: ${ms.triggers.join(" | ")}
Visual: ${ms.visualGuidance}
Tone: ${ms.copyTone}
Examples: ${ms.exampleHeadlines.join(" | ")}`).join("\n\n---\n\n");
}

export function getMindstateById(id: string): MindstateProfile | undefined {
  return MINDSTATE_PROFILES.find(ms => ms.id === id);
}

export function getMindstatesByApproach(approach: "cautious" | "optimistic"): MindstateProfile[] {
  return MINDSTATE_PROFILES.filter(ms => ms.approach === approach);
}

export function getMindstatesByMotivation(motivation: string): MindstateProfile[] {
  return MINDSTATE_PROFILES.filter(ms => ms.motivation === motivation);
}